# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  name: Rajesh Custom Agent Pool

variables: 
 - name: developBranch
   value: 'refs/heads/develop'
steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'avio-settings.xml'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '1.11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  displayName: 'Store Artifact: Copy Jar to: $(build.artifactstagingdirectory)'
  condition: eq(variables['Build.SourceBranch'], variables['developBranch'])
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/target/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: CopyFiles@2
  displayName: 'Store Artifact: Copy Pom to: $(build.artifactstagingdirectory)'
  condition: eq(variables['Build.SourceBranch'], variables['developBranch'])
  inputs:
   SourceFolder: '$(system.defaultworkingdirectory)'
   Contents: 'pom.xml'
   TargetFolder: '$(build.artifactstagingdirectory)'    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: eq(variables['Build.SourceBranch'], variables['developBranch'])

